#ifndef STATE_H
#define STATE_H

typedef enum {
    STATE_OK,
    STATE_BAD_ALLOCATION,
    STATE_PARSE_ERROR,
    STATE_FILE_ERROR,
    STATE_USER_NOT_FOUND,
    STATE_USERNAME_TAKEN,
    STATE_INVALID_PIN,
    STATE_INVALID_USERNAME,
    STATE_INVALID_DATE,
    STATE_INVALID_FLAG,
    STATE_INVALID_LIMIT,
    STATE_DATE_IN_FUTURE,
} State;

#endif
